sudo: required
services:
  - docker

before_install:
  - docker build -t carlosdelros/frontend-test -f ./frontend/Dockerfile.dev ./frontend


script:
  - docker run carlosdelros/frontend-test npm test -- --coverage


after_success:
  - docker build -t carlosdelros/multi-container-frontend ./frontend
  - docker build -t carlosdelros/multi-container-nginx ./nginx
  - docker build -t carlosdelros/multi-container-backend ./backend
  - docker build -t carlosdelros/multi-container-worker ./worker
  
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push to dockerhub
  - docker push carlosdelros/multi-container-frontend
  - docker push carlosdelros/multi-container-nginx
  - docker push carlosdelros/multi-container-backend
  - docker push carlosdelros/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-container-kubernetes-tutorial
  env: MultiContainerKubernetesTutorial-env
  bucket_name: elasticbeanstalk-us-east-1-973824132018
  bucket_path: multi-container-kub
on:
  branch: master
access_key_id: $AWS_BEANSTALK_ACCESS_KEY
secret_access_key:
  secure: $AWS_BEANSTALK_SECRET_KEY
 
